# DO NOT EDIT! Automatically generated by scripts/generate_providers_and_account_vars.py
# To rebuild variables-accounts.tf, execute the generate_providers_and_account_vars GitHub workflow.


variable "account_Production" {
  type    = string
  default = "111111111111"
}

variable "account_Audit" {
  type    = string
  default = "222222222222"
}
