name: "Generate Providers and Account Variables"

permissions:
  id-token: write
  contents: write # This is required for actions/checkout
  pull-requests: write

on:
  schedule:
    # Runs "10:45AM UTC Daily" (see https://crontab.guru)
    - cron: "45 10 * * *"
  workflow_dispatch:

jobs:
  generate-providers-and-account-vars:
    name: "Generate Providers and Account Variables"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Source Environment Variables
        id: dotenv
        uses: falti/dotenv-action@v1.0.4
        with:
          path: ".github/workflows/.env"

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip" # caching pip dependencies
      - run: pip install -r scripts/requirements.txt

      # - name: Get GitHub Apps Token # This enables access to Terraform modules in internal/private repos
      #   id: get_token
      #   uses: machine-learning-apps/actions-app-token@master
      #   with:
      #     APP_PEM: ${{ secrets.ORG_REPO_READ_PRIVATE_KEY }}
      #     APP_ID: ${{ secrets.ORG_REPO_READ_APP_ID }}
      #   # Doc: https://github.com/machine-learning-apps/actions-app-token

      - name: Configure AWS Credentials for reading state
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ steps.dotenv.outputs.aws_account_id }}:role/github-workflow-rvm
          role-session-name: ${{ github.actor }}_${{ github.job }}
          aws-region: ${{ steps.dotenv.outputs.aws_region }}

      - name: Generate providers
        run: python3 scripts/generate_providers_and_account_vars.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # ${{ steps.get_token.outputs.app_token }}

      - run: echo "DATE=$(date --iso-8601)" >> $GITHUB_ENV

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          branch: "feature/account-list-update"
          title: "Generate Providers and Account Variables"
          commit-message: Automatically updated providers.tf and variables-account.tf files
          add-paths: |
            *.tf

      # - name: Commit
      #   uses: stefanzweifel/git-auto-commit-action@v4
      #   with:
      #     branch: "main"
      #     push_options: '--force'
      #     commit_message: "AWS Providers as of ${{ env.DATE }}"
      #     file_pattern: 'dev-control-tower/providers.tf dev-control-tower/variables-accounts-dev-control-tower.tf prod-control-tower/providers.tf prod-control-tower/variables-accounts-prod-control-tower.tf'
